### ISSUE TITLE
Reencode Profile Image

### ISSUE THREAD

**Issue by nperez0111** [NSuri1/suriosity.com#1]
Your profile image is **HUGE** (2537x2537) it needs to be resized preferably to a jpeg with progressive scan settings. 
The size it should be set to is the largest that it'll ever be looking at it on a desktop, So with how you have it maybe 600x600? 800x800 max.

**Comment by nperez0111** [comment]
On second thought you still want the transparency of the image so keep it as a png but reduce the quality to maybe 80 percent. Speed is a major factor in websites

**Comment by NSuri1** [comment]
Thanks for advice, I resized the omg to 507x519
