### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by nperez0111** [NSuri1/suriosity.com#2]
I like the links at the bottom how they are visually separated from everything else but I could've just thought them to be just any old image. 

To fix this you also need to visually separate the links section from the lorem ispum paragraph.
Two options:

1. Bump the font-size and bolden it
2. Do a horizontal line separator so the person reading knows this has to do with a different topic

**Comment by NSuri1** [comment]
Used bottom border to separate sections of site!
