### ISSUE TITLE
HTTP/S Issue

### ISSUE THREAD

**Issue by nperez0111** [NSuri1/suriosity.com#5]
Your are loading the meyer reset file from a website not using https which throws an error in chrome. To fix that all you need to do is save the meyer reset and load your copy of the meyer reset since your website is being served over https.

**Comment by nperez0111** [comment]
![image of issue](https://lh3.googleusercontent.com/aO-HpyaxudhN-Oout1HUUO7C_kuOArG2Rz9o2vY7fdqaYz1mA66UTn1TsobLoVpa25amGSI3Tjtb0YJdZxHLMjUSDWNMaVNMF8NQD4TdhY3QBL0HJ8rtRMc5yPWQOtVbBarqyR3iRrkRol8-J_SULXVZhdEtLzd6_zTfOrPCx3xW5tdXRmbAwuEebnn3hJXMzhyJjdky453cQLFdFAtOQZcp62DCLlisRYYnX-WemFw205L7KbtebsHdzCLIMT6zIufUOeVZHJUZnxgWxsM0floeEFnsv3rjfMc4ieUN6117r-PXK2zozR6585AGXuicxG7nD71Zndp4S5PH68U8gOFVZtmgazsgzzcQFXzsgH1eGX7gVmLmSU-ftK6hWAqBJxAaogHeit7yp1FKvBK1eNQVxK4AHlQHAWeYtRD9f3SCB5u7DveO13avuStteMW0yX4pe922yap9y1dff6cIK3IVfcjgCtiXCChbkoDEGr-rXhEeIr3rzf9ECqR64REPKqw8tEllNLW9O94RYAmLld9U0MOwk9i_MFE3KJtV7jFVkS9HTJqB40JjBAzh7IrmOKpWkexbk-XqHRmxcR832SWDvUdSs18nWzkagTeZSMN4V2wD88XxNw=w1287-h800-no)
https://goo.gl/photos/XCaqaaJ3KdzDV6W2A

**Comment by NSuri1** [comment]
Removed the css reset
